package com.wutsi.blog.app.util

class PageName{
    companion object {
        const val BLOG = "page.blog"
        const val EDITOR = "page.editor"
        const val ERROR_400 = "page.error.400"
        const val ERROR_403 = "page.error.403"
        const val ERROR_404 = "page.error.404"
        const val ERROR_500 = "page.error.500"
        const val HOME = "page.home"
        const val LOGIN = "page.login"
        const val RUN_AS = "page.run.as"
        const val LEGAL_ABOUT = "page.legal.about"
        const val LEGAL_TERMS = "page.legal.about"
        const val LOGOUT = "page.logout"
        const val MAIL_UNSUBSCRIBE = "page.mail.unsubscribe"
        const val WRITER = "page.writer"
        const val READ = "page.read"
        const val SETTINGS = "page.settings"
        const val STORY_DRAFT = "page.story.draft"
        const val STORY_READABILITY = "page.story.readability"
        const val STORY_TAG = "page.story.tag"
        const val PARTNER = "page.partner"
        const val PARTNER_JOIN = "page.partner.join"
        const val PARTNER_PAYMENT = "page.partner.payment"
        const val PARTNER_SUCCESS = "page.partner.success"
        const val STORY_PREVIEW = "page.story.preview"
        const val STORY_PUBLISHED = "page.story.published"
        const val STORY_SYNDICATE = "page.story.syndicate"
        const val STATS_STORY = "page.stats.story"
        const val STATS_USER = "page.stats.user"
        const val WELCOME = "page.welcome"
        const val WELCOME_FULLNAME = "page.welcome.fullname"
        const val WELCOME_EMAIL = "page.welcome.fullname"
        const val WELCOME_BIOGRAPHY = "page.welcome.biography"
        const val WELCOME_PICTURE = "page.welcome.picture"
        const val WELCOME_SUCCESS = "page.welcome.success"
    }
}
